-- Analysis content model (docs/MKTBD_SPEC.md sections 4 and 8) plus its
-- carousel slides (section 5). Tag relationships are added later, in
-- 20261003000006_content_tags.sql, once public.tags also exists.

create table public.analyses (
  id uuid primary key default gen_random_uuid(),
  title text not null check (btrim(title) <> ''),
  slug text not null,
  publication_date date not null default current_date,
  linkedin_url text check (linkedin_url is null or linkedin_url ~* '^https?://'),
  status public.content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint analyses_slug_key unique (slug),
  -- Enforced here (not just generated by the future Admin UI), per
  -- MKTBD_SPEC.md section 4: "database must still enforce uniqueness."
  -- The format check keeps slugs URL-safe regardless of what generated
  -- them.
  constraint analyses_slug_format check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

create index analyses_status_idx on public.analyses (status);

create trigger analyses_set_updated_at
  before update on public.analyses
  for each row execute function public.set_updated_at();

alter table public.analyses enable row level security;

create policy "analyses_select_published_or_admin"
  on public.analyses for select
  using (status = 'published' or public.is_admin());

create policy "analyses_admin_write"
  on public.analyses for all
  using (public.is_admin())
  with check (public.is_admin());

-- Carousel slides. Images themselves live in Supabase Storage
-- (editorial-media bucket, see 20261003000008_storage.sql); this table only
-- stores ordering + the storage path.
create table public.analysis_slides (
  id uuid primary key default gen_random_uuid(),
  analysis_id uuid not null references public.analyses (id) on delete cascade,
  storage_path text not null check (btrim(storage_path) <> ''),
  position integer not null check (position >= 0),
  created_at timestamptz not null default now(),
  -- Deferrable: a future drag-and-drop reorder will update many rows'
  -- positions in one transaction, which can transiently collide
  -- (e.g. swapping 0 and 1 via two UPDATEs) before the final state is
  -- valid. INITIALLY DEFERRED means the uniqueness check only runs at
  -- COMMIT, not after each individual UPDATE.
  constraint analysis_slides_unique_position
    unique (analysis_id, position) deferrable initially deferred
);

comment on table public.analysis_slides is
  'Ordered carousel slides for an Analysis. position is 0-based and must be
   deterministic/gap-tolerant -- the Admin UI is responsible for keeping it
   dense, this table only guarantees no two slides of the same Analysis
   share a position.';

create index analysis_slides_analysis_id_idx on public.analysis_slides (analysis_id);

alter table public.analysis_slides enable row level security;

create policy "analysis_slides_select_published_or_admin"
  on public.analysis_slides for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.analyses a
      where a.id = analysis_slides.analysis_id and a.status = 'published'
    )
  );

create policy "analysis_slides_admin_write"
  on public.analysis_slides for all
  using (public.is_admin())
  with check (public.is_admin());
